workflows:
  build_ios_app:
    name: Build iOS app (no signing)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "ios-pwnagotchi.xcodeproj"
        XCODE_SCHEME: "ios-pwnagotchi WatchKit App"
        BUILD_CONFIGURATION: "Release"
      xcode: 15.4
    scripts:
      - name: Clean previous build
        script: |
          rm -rf build || true

      - name: Build iOS app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$BUILD_CONFIGURATION" \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build \
            CONFIGURATION_BUILD_DIR=$CM_BUILD_DIR/build

      - name: Package .app as artifact
        script: |
          mkdir -p $CM_BUILD_DIR/artifacts
          cp -r $CM_BUILD_DIR/build/*.app $CM_BUILD_DIR/artifacts/
    artifacts:
      - artifacts/*.app
    publishing:
      email:
        recipients:
          - your@email.com

