name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: List available schemes
        run: xcodebuild -list -project "ios-pwnagotchi.xcodeproj"

      - name: Build unsigned iOS app
        run: |
          xcodebuild \
            -project "ios-pwnagotchi.xcodeproj" \
            -scheme "ios-pwnagotchi WatchKit App" \
            -sdk iphoneos \
            -configuration Release \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CONFIGURATION_BUILD_DIR=$PWD/build

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/*.app Payload/
          zip -r ios-pwnagotchi.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-pwnagotchi.ipa
          path: ios-pwnagotchi.ipa
